# Generated by Django 5.2.15 on 2026-06-13 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_aboutfeature_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.CharField(default='General', max_length=100),
            preserve_default=False,
        ),
    ]
